LDML=bcc-Arab-t-k0-cldr-phonetic.ldml
KEYMAN=balochi_phonetic.kmn
#HAS_REORDER=True
#REORDER=reorder.xml
BASE=shared/en-us-win.xml
TESTS=test1.xml test2.xml
LOCALE="bcc-Arab"
NAME="Balochi Phonetic"
#OPTIONS=

include ../keyboards.mk
