KEYMAN=balochi_phonetic.kmn
LDML=balochi_phonetic.ldml
#HAS_REORDER=True
#REORDER=reorder.xml
BASE=shared/en-us-win.xml
TESTS=test1.xml test2.xml
LOCALE="bcc-Arab"
NAME="Balochi Phonetic"
#OPTIONS=

include ../keyboards.mk
