LDML = lep-t-k0-cldr-sil.ldml
KEYMAN = sil_lepcha.kmn
TESTS = test1.xml test2.xml
REORDER = sil-lepcha_reorder.xml
BASE = shared/en-us-win.xml
LOCALE = lep-Lepc
NAME = "SIL Lepcha"

include ../keyboards.mk
