LDML = und-Ethi-ET-t-k0-cldr-powerg.ldml
KEYMAN = sil_ethiopic_power_g.kmn
# HAS_REORDER = True
# REORDER = reorder.xml
BASE = shared/en-us-win.xml
TESTS = test1.xml test2.xml
LOCALE = amh-Ethi
NAME="SIL Power-G Ethiopic"

include ../keyboards.mk

