LDML=bn-t-k0-cldr-phonetic.ldml
KEYMAN=sil_bengali_phonetic.kmn
HAS_REORDER = True
# REORDER=
BASE=shared/en-us-win.xml
TESTS=test1.xml
LOCALE=bn-Beng
NAME="SIL Bengali Phonetic"

include ../keyboards.mk

