LDML = und-Lana-t-k0-cldr-boonkit.ldml
KEYMAN = boonkit.kmn
HAS_REORDER = True
#REORDER = reorder.xml
BASE = shared/en-us-win.xml
TESTS = test1.xml test2.xml
LOCALE = nod-Lana
NAME = "Boonkit"
OPTIONS = -C 200B

include ../keyboards.mk

