LDML=ccp-t-k0-cldr-easy.ldml
KEYMAN=easy_chakma.kmn
HAS_REORDER=True
#REORDER=easy_chakma_reorder.xml
BASE=shared/en-us-win.xml
TESTS=test1.xml test2.xml
LOCALE=ccp-Cakm
NAME="Easy Chakma"
OPTIONS=-C 200B

include ../keyboards.mk
