LDML = khmer_angkor.ldml
KEYMAN = khmer_angkor.kmn
IMPORT = khmer_angkor_import.ldml
HAS_REORDER = True
BASE = shared/en-us-win.xml
TESTS = basics.xml # keyman_tests.xml
LOCALE = kh-Khmr
NAME="Khmer Angkor"
TESTOPTIONS = -b
debug=True

include ../keyboards.mk

