LDML = khmer_angkor.ldml
KEYMAN = khmer_angkor.kmn
IMPORT = khmer_angkor_import.ldml
HAS_REORDER = True
BASE = shared/en-us-win.xml
TESTS = basics.xml
LOCALE = kh-Khmr
NAME="Khmer Angkor"

include ../keyboards.mk

