LDML = sil-mywinext.ldml
KEYMAN = sil_myanmar_mywinext.kmn
# HAS_REORDER = True
REORDER = reorder.xml
BASE = shared/en-us-win.xml
TESTS = test1.xml
LOCALE = my-Mymr
NAME="Myanmar Windows Extended (SIL)"

include ../keyboards.mk

