LDML = gff-tigrinya-eritrea.ldml
KEYMAN = gff_tigrinya_eritrea.kmn
# HAS_REORDER = True
# REORDER = reorder.xml
BASE = shared/en-us-win.xml
TESTS = test1.xml
LOCALE = ti-ET
NAME="GFF Tigrinya Eritrea"

include ../keyboards.mk

