LDML = ti-ER-t-k0-cldr-gff.ldml
KEYMAN = gff_tigrinya_eritrea.kmn
# HAS_REORDER = True
# REORDER = reorder.xml
BASE = shared/en-us-win.xml
TESTS = test0.xml test1.xml test2.xml test3.xml
LOCALE = ti-ET
NAME="GFF Tigrinya Eritrea"

include ../keyboards.mk

