KEYMAN=sil_shan.kmn
LDML=sil_shan.ldml
HAS_REORDER = True
#REORDER=sil_shan_reorder.xml
BASE=shared/en-us-win.xml
TESTS=test1.xml test2.xml test3.xml
LOCALE=shn-Mymr
NAME="Shan (SIL)"
OPTIONS = -C 200B

include ../keyboards.mk

