LDML = panafrica_us.ldml
KEYMAN = sil_pan_africa_positional.kmn
# HAS_REORDER = True
# REORDER = reorder.xml
BASE = shared/en-us-win.xml
TESTS = test1.xml
LOCALE = und-Latn
NAME="Pan Africa Positional (SIL)"

include ../keyboards.mk

