LDML = vai-t-k0-cldr-sil.ldml
KEYMAN = sil_vai.kmn
# HAS_REORDER = True
# REORDER = reorder.xml
BASE = shared/en-us-win.xml
TESTS = test1.xml test2.xml
LOCALE = vai-Vaii
NAME="SIL Vai"

include ../keyboards.mk

