LDML = sil-deva-phonetic.ldml
KEYMAN = sil_devanagari_phonetic.kmn
BASE = shared/en-us-win.xml
TESTS = test1.xml
LOCALE = hi-Deva
HAS_REORDER = True
NAME="SIL Devanagari Phonetic"

include ../keyboards.mk

